plugins {
  id 'java'
  id 'application'
  id 'com.github.johnrengelman.shadow' version '8.1.1'
}

repositories { mavenCentral() }

dependencies {
  implementation "com.openai:openai-java:4.13.0"
}


application {
  mainClass = 'app.Main'
}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}